import {
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
  type ISectionOptions,
} from 'docx';

export async function buildDocx(title: string, source: string): Promise<Uint8Array> {
  const children = documentChildren(source);
  const sections: ISectionOptions[] = [{ children }];
  const document = new Document({
    creator: 'Agent Harness',
    title,
    description: 'Generated by Agent Harness',
    sections,
  });
  return new Uint8Array(await Packer.toBuffer(document));
}

function documentChildren(source: string): Array<Paragraph | Table> {
  const lines = source.replace(/\r\n/g, '\n').split('\n');
  const output: Array<Paragraph | Table> = [];
  let index = 0;
  while (index < lines.length) {
    const line = lines[index] ?? '';
    if (!line.trim()) {
      output.push(new Paragraph(''));
      index += 1;
      continue;
    }
    const heading = /^(#{1,6})\s+(.+)$/.exec(line);
    if (heading) {
      output.push(
        new Paragraph({
          heading: headingLevel(heading[1]?.length ?? 1),
          children: inlineRuns(heading[2] ?? ''),
        }),
      );
      index += 1;
      continue;
    }
    if (isTable(lines, index)) {
      const rows = [cells(line)];
      index += 2;
      while (index < lines.length && lines[index]?.includes('|') && lines[index]?.trim()) {
        rows.push(cells(lines[index] ?? ''));
        index += 1;
      }
      output.push(
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: rows.map(
            (row, rowIndex) =>
              new TableRow({
                children: row.map(
                  (value) =>
                    new TableCell({
                      children: [
                        new Paragraph({
                          children: [new TextRun({ text: value, bold: rowIndex === 0 })],
                        }),
                      ],
                    }),
                ),
              }),
          ),
        }),
      );
      continue;
    }
    const unordered = /^\s*[-*+]\s+(.+)$/.exec(line);
    if (unordered) {
      output.push(
        new Paragraph({ bullet: { level: 0 }, children: inlineRuns(unordered[1] ?? '') }),
      );
      index += 1;
      continue;
    }
    const ordered = /^\s*(\d+)\.\s+(.+)$/.exec(line);
    if (ordered) {
      output.push(new Paragraph({ children: inlineRuns(`${ordered[1]}. ${ordered[2]}`) }));
      index += 1;
      continue;
    }
    output.push(new Paragraph({ children: inlineRuns(line.trim()) }));
    index += 1;
  }
  return output;
}

function inlineRuns(value: string): TextRun[] {
  const parts = value.split(/(\*\*[^*]+\*\*|`[^`]+`)/g).filter(Boolean);
  return parts.map((part) => {
    if (part.startsWith('**') && part.endsWith('**')) {
      return new TextRun({ text: part.slice(2, -2), bold: true });
    }
    if (part.startsWith('`') && part.endsWith('`')) {
      return new TextRun({ text: part.slice(1, -1), font: 'Consolas' });
    }
    return new TextRun(part);
  });
}

function headingLevel(level: number): (typeof HeadingLevel)[keyof typeof HeadingLevel] {
  return [
    HeadingLevel.HEADING_1,
    HeadingLevel.HEADING_2,
    HeadingLevel.HEADING_3,
    HeadingLevel.HEADING_4,
    HeadingLevel.HEADING_5,
    HeadingLevel.HEADING_6,
  ][Math.max(0, Math.min(level - 1, 5))] as (typeof HeadingLevel)[keyof typeof HeadingLevel];
}

function isTable(lines: string[], index: number): boolean {
  return Boolean(lines[index]?.includes('|') && /^\s*\|?\s*:?-{3,}/.test(lines[index + 1] ?? ''));
}

function cells(line: string): string[] {
  return line
    .trim()
    .replace(/^\||\|$/g, '')
    .split('|')
    .map((value) => value.trim());
}
